name: gogeomatics-workshop
channels:
  - conda-forge
dependencies:
- python=3.11
- pdal
- python-pdal
- pystac
- jupyter
- pip
- pip:
  - requests
  - folium
  - pyproj
  - shapely
  - pyproj 
  - pillow
  - stactools-canelevation
